[tool.poetry]
name = "uvicorn-poetry"
version = "2.1.0"
description = "Docker image with Uvicorn ASGI server for running Python web applications on Kubernetes. Uses Poetry for managing dependencies and setting up a virtual environment."
authors = ["Max Pfeiffer <max@maxpfeiffer.ch>"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.9.*"
click = "8.1.3"
docker = "6.0.1"

[tool.poetry.dev-dependencies]
pytest = "7.3.1"
pytest-cov = "4.0.0"
coverage = "7.2.3"
requests = "2.29.0"
black = "23.3.0"
pre-commit = "3.2.2"
semver = "3.0.0"
pylint = "2.17.3"
testcontainers = "3.7.1"

# https://docs.pytest.org/en/latest/reference/customize.html

[tool.poetry.group.dev.dependencies]
bcrypt = "^4.0.1"

[tool.pytest.ini_options]
testpaths = [
    "tests",
]

# https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#configuration-via-a-file
[tool.black]
line-length = 80
target-version = ["py39"]

[tool.pylint.main]
errors-only = true
recursive = "y"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
