name: Publish Images

on:
  push:
    tags:
      - '*'

jobs:
  publish-all-images:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Get Git Commit Tag Name
        uses: olegtarasov/get-tag@v2.1
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.11
      - name: Install dependencies
        run: |
          poetry config virtualenvs.in-project true
          poetry install --no-root
      - name: Publish Image to Docker Hub
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: |
          source .venv/bin/activate
          python publish.py
